/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package charityapp;

/**
 *
 * @author Bogdan Postolachi
 */
import java.util.ArrayList;

public class TotalDonationHistory extends Charity {

    
    
    private ArrayList<Donations> allDonations;  // list of all Donations objects (one per user)

    
    
    //default constructor
    // constructor initializes this field with a new and empty ArrayList
    public TotalDonationHistory() {
        allDonations = new ArrayList<>();
    }
    
    

    // add new user's donation
    public void addDonation(String name, double amount, String dob, String message) {  //method declaration, parameters in brackets
        // check if user already exists
        for (Donations donation : allDonations) {  //loops through allDonations list which stores Donations objects for each user
            
            //If the user exists: calls addDonation method of the existing Donations object to add the new donation amount to their history
            if (donation.getName().equalsIgnoreCase(name)) {
                donation.addDonation(amount);  // Update existing user's donation
                return;
            }
        }

        // add new user with their first donation
        Donations newDonation = new Donations(userName, password, name, amount, dob, message);
        allDonations.add(newDonation);
    }
    
    

    // display all donations from all users
    //generate and return a formatted string that displays the details of all donations made by all users
    public String displayTotalDonations() {
        if (allDonations.isEmpty()) {  //check if allDonations is empty
            return "No donations have been made.";
        }

        String result = "Total Donations:\n";   //string accumulates the details of all donations
        for (Donations donation : allDonations) {
            result += donation.getDetails() + "\n";
        }
        return result;  //returns final string

    }

    // calculate the total of all donations
    //method computes and returns the total sum of all donations made by all users stored in the TotalDonationHistory class
    public double calculatedTotal() {
        double total = 0; //variable initialized as 0 will hold the sum oh all donations
        for (Donations donation : allDonations) {  //each Donations object represents the donation history of a single user
            for (Double amount : donation.getDonationAmounts()) { //nested loop
                total += amount;
            }
        }
        return total; //returns final sum
    }

    
    //Getter
    public ArrayList<Donations> getAllDonations() {
        return allDonations;
    }
    
    /*   //Generated by NetBeans
    Object getAllDonations() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    Donations getUserDonation(String userName) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }*/
}
